name: injection

services:
  redis:
    image: redis:7.2.1
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      start_period: 10s
      retries: 3
      timeout: 30s
      interval: 30s

  postgres:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
      
volumes:
  redis_volume:
  postgresql_volume: