name: injection

services:
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8000:80"
    environment:
      - REWRITE_FROM=/api
      - REWRITE_TO=""
      - BACKEND_HOST=api
      - BACKEND_PORT=8080

  api:
    image: node:latest
    volumes:
      - ./api:/app
    command: ["npx", "http-server"]
    working_dir: /srv
    ports:
      - "8080:8080"

  